// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "openapi": "3.0.0",
  "info": {
    "description": "This is API documentation on DataBx Semeru1 Microservices",
    "version": "1.0.0",
    "title": "DataBx Semeru1 Microservices",
    "contact": {
      "email": "akbar.muhammadakbarmaulana@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "tags": [
    {
      "name": "city",
      "description": "Simple acces to list of city available"
    },
    {
      "name": "province",
      "description": "Same as city, instead of province"
    }
  ],
  "paths": {
    "/select/city/id": {
      "post": {
        "tags": [
          "city"
        ],
        "summary": "Get list city by given id",
        "description": "TThis should be return only one city ya",
        "operationId": "GetCityById",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Cities"
        },
        "responses": {
          "200": {
            "description": "GetCityById success, with given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    },
    "/select/city/name": {
      "post": {
        "tags": [
          "city"
        ],
        "summary": "Get list city by given name",
        "description": "You can create lose search with this, this should be return related one",
        "operationId": "GetCityByName",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Cities"
        },
        "responses": {
          "200": {
            "description": "GetCityByName success, with given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    },
    "/select/city/province": {
      "post": {
        "tags": [
          "city"
        ],
        "summary": "Get list city in certain province",
        "description": "TThis should be return all city in given province",
        "operationId": "GetCityByProvince",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Cities"
        },
        "responses": {
          "200": {
            "description": "GetCityByProvince success, with given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    },
    "/select/city/all": {
      "post": {
        "tags": [
          "city"
        ],
        "summary": "Get ALL list city",
        "description": "Carefull on using limit and offset ya",
        "operationId": "GetAllCity",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Cities"
        },
        "responses": {
          "200": {
            "description": "GetAllCity success, with given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    },
    "/select/province/id": {
      "post": {
        "tags": [
          "province"
        ],
        "summary": "Get single province by id",
        "description": "Single return ya, it should be",
        "operationId": "getProvinceById",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Provinces"
        },
        "responses": {
          "200": {
            "description": "getProvince returned province la based on given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    },
    "/select/province/all": {
      "post": {
        "tags": [
          "province"
        ],
        "summary": "Get all province from table",
        "description": "Single response get all province name, define offset to shift through available data",
        "operationId": "getAllProvince",
        "security": [
          {"basicAuth":  []}
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/xClientId"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Provinces"
        },
        "responses": {
          "200": {
            "description": "getAllProvince returned province based on given request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseSuccess"
                }
              }
            }
          },
          "400": {
            "description": "Check request, body not comply with request rules",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          },
          "401": {
            "description": "You are not permitted!"
          },
          "500": {
            "description": "General error, system cannot tell you what wrongs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseError"
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:7716/semeru1/api/v1"
    }
  ],
  "components": {
    "requestBodies": {
      "Cities": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/RequestCity"
            }
          }
        }
      },
      "Provinces": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/RequestProvince"
            }
          }
        }
      }
    },
    "schemas": {
      "RequestCity": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "request_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
          },
          "data": {
            "type": "object",
            "properties": {
              "city_id": {
                "type": "integer",
                "format": "uint",
                "maxLength": 3,
                "minimum": 1
              },
              "city_name": {
                "type": "string"
              },
              "city_province": {
                "type": "integer",
                "format": "uint",
                "maxLength": 2
              },
              "limit": {
                "type": "integer",
                "format": "uint",
                "minimum": 1,
                "maxLength": 3
              },
              "offset": {
                "type": "integer",
                "format": "int",
                "maxLength": 3
              }
            }
          }
        }
      },
      "RequestProvince": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "request_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
          },
          "data": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "province_id": {
                "type": "integer",
                "maximum": 34,
                "minimum": 1,
                "format": "uint"
              },
              "province_name": {
                "type": "string",
                "maxLength": 64,
                "format": "uint",
                "pattern": "^[A-Za-z]$"
              },
              "limit": {
                "type": "integer",
                "maximum": 64,
                "minimum": 1,
                "format": "uint"
              },
              "offset": {
                "type": "integer",
                "format": "int"
              }
            }
          }
        }
      },
      "ResponseSuccess": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "response_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
          },
          "request_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
          },
          "success": {
            "type": "boolean"
          },
          "response_time": {
            "type": "string",
            "maxLength": 64,
            "pattern": "^[0-9]$"
          },
          "message": {
            "type": "string",
            "maxLength": 256,
            "pattern": "^.$"
          },
          "data": {
            "type": "object",
            "additionalProperties": true,
            "maxProperties": 64
          }
        }
      },
      "ResponseError": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "response_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"

          },
          "request_id": {
            "type": "string",
            "maxLength": 36,
            "pattern": "[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}"
          },
          "success": {
            "type": "boolean"
          },
          "response_time": {
            "type": "string",
            "maxLength": 64,
            "pattern": "^[0-9]$"
          },
          "error": {
            "type": "string",
            "maxLength": 256,
            "pattern": "^.$"
          }
        }
      }
    },
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    },
    "parameters": {
      "xClientId": {
        "name": "X-Client-ID",
        "in": "header",
        "description": "Custom Id that defines you as caller",
        "required": false,
        "schema": {
          "type": "string",
          "maxLength": 32,
          "pattern": "[A-Za-z0-9]{32}"
        }
      }
    }
  },
  "security": [
    {
      "basicAuth": []
    }
  ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
